const contryCodeToPortuguese = {
  AF: 'Afeganistão',
  ZA: 'África do Sul',
  AL: 'Albânia',
  DE: 'Alemanha',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antártica',
  AG: 'Antígua e Barbuda',
  SA: 'Arábia Saudita',
  DZ: 'Argélia',
  AR: 'Argentina',
  AM: 'Armênia',
  AW: 'Aruba',
  AU: 'Austrália',
  AT: 'Áustria',
  AZ: 'Azerbaijão',
  BS: 'Bahamas',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BH: 'Bahrein',
  BY: 'Bielorrússia',
  BE: 'Bélgica',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermudas',
  BO: 'Bolívia',
  BA: 'Bósnia e Herzegovina',
  BW: 'Botsuana',
  BR: 'Brasil',
  BN: 'Brunei',
  BG: 'Bulgária',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  BT: 'Butão',
  CV: 'Cabo Verde',
  CM: 'Camarões',
  KH: 'Camboja',
  CA: 'Canadá',
  QA: 'Catar',
  KZ: 'Cazaquistão',
  EA: 'Ceuta e Melilha',
  TD: 'Chade',
  CL: 'Chile',
  CN: 'China',
  CY: 'Chipre',
  SG: 'Cingapura',
  CO: 'Colômbia',
  KM: 'Comores',
  CG: 'Congo',
  KP: 'Coreia do Norte',
  KR: 'Coreia do Sul',
  CI: 'Costa do Marfim',
  CR: 'Costa Rica',
  HR: 'Croácia',
  CU: 'Cuba',
  CW: 'Curaçao',
  DG: 'Diego Garcia',
  DK: 'Dinamarca',
  DJ: 'Djibuti',
  DM: 'Dominica',
  EG: 'Egito',
  SV: 'El Salvador',
  AE: 'Emirados Árabes Unidos',
  EC: 'Equador',
  ER: 'Eritreia',
  SK: 'Eslováquia',
  SI: 'Eslovênia',
  ES: 'Espanha',
  EE: 'Estônia',
  ET: 'Etiópia',
  FJ: 'Fiji',
  PH: 'Filipinas',
  FI: 'Finlândia',
  FR: 'França',
  GA: 'Gabão',
  GM: 'Gâmbia',
  GH: 'Gana',
  GE: 'Geórgia',
  GS: 'Geórgia do Sul e Ilhas Sandwich do Sul',
  GI: 'Gibraltar',
  GD: 'Granada',
  GR: 'Grécia',
  GL: 'Groenlândia',
  GP: 'Guadalupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GY: 'Guiana',
  GF: 'Guiana Francesa',
  GN: 'Guiné',
  GW: 'Guiné-Bissau',
  GQ: 'Guiné Equatorial',
  HT: 'Haiti',
  HN: 'Honduras',
  HU: 'Hungria',
  YE: 'Iêmen',
  BV: 'Ilha Bouvet',
  IM: 'Ilha de Man',
  NF: 'Ilha Norfolk',
  CX: 'Ilha Christmas',
  CP: 'Ilha Clipperton',
  AC: 'Ilha de Ascensão',
  AX: 'Ilhas Aland',
  IC: 'Ilhas Canárias',
  KY: 'Ilhas Cayman',
  CC: 'Ilhas Cocos (Keeling)',
  CK: 'Ilhas Cook',
  FO: 'Ilhas Faroé',
  FK: 'Ilhas Malvinas',
  MP: 'Ilhas Marianas do Norte',
  MH: 'Ilhas Marshall',
  UM: 'Ilhas Menores Distantes dos Estados Unidos',
  PN: 'Ilhas Pitcairn',
  SB: 'Ilhas Salomão',
  TC: 'Ilhas Turks e Caicos',
  VG: 'Ilhas Virgens Britânicas',
  VI: 'Ilhas Virgens Americanas',
  IN: 'Índia',
  ID: 'Indonésia',
  IR: 'Irã',
  IQ: 'Iraque',
  IE: 'Irlanda',
  IS: 'Islândia',
  IL: 'Israel',
  IT: 'Itália',
  JM: 'Jamaica',
  JP: 'Japão',
  JE: 'Jersey',
  JO: 'Jordânia',
  KW: 'Kuwait',
  LA: 'Laos',
  LS: 'Lesoto',
  LV: 'Letônia',
  LB: 'Líbano',
  LR: 'Libéria',
  LY: 'Líbia',
  LI: 'Liechtenstein',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  MO: 'Macau',
  MK: 'Macedônia do Norte',
  MG: 'Madagáscar',
  MY: 'Malásia',
  MW: 'Malaui',
  MV: 'Maldivas',
  ML: 'Mali',
  MT: 'Malta',
  MA: 'Marrocos',
  MQ: 'Martinica',
  MU: 'Maurício',
  MR: 'Mauritânia',
  YT: 'Mayotte',
  MX: 'México',
  FM: 'Micronésia',
  MZ: 'Moçambique',
  MD: 'Moldávia',
  MC: 'Mônaco',
  MN: 'Mongólia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MM: 'Mianmar (Birmânia)',
  NA: 'Namíbia',
  NR: 'Nauru',
  NP: 'Nepal',
  NI: 'Nicarágua',
  NE: 'Níger',
  NG: 'Nigéria',
  NU: 'Niue',
  NO: 'Noruega',
  NC: 'Nova Caledônia',
  NZ: 'Nova Zelândia',
  OM: 'Omã',
  NL: 'Países Baixos',
  PW: 'Palau',
  PA: 'Panamá',
  PG: 'Papua-Nova Guiné',
  PK: 'Paquistão',
  PY: 'Paraguai',
  PE: 'Peru',
  PF: 'Polinésia Francesa',
  PL: 'Polônia',
  PR: 'Porto Rico',
  PT: 'Portugal',
  KE: 'Quênia',
  KG: 'Quirguistão',
  KI: 'Quiribati',
  GB: 'Reino Unido',
  CF: 'República Centro-Africana',
  DO: 'República Dominicana',
  CD: 'República Democrática do Congo',
  CZ: 'República Tcheca',
  RE: 'Reunião',
  RO: 'Romênia',
  RW: 'Ruanda',
  RU: 'Rússia',
  EH: 'Saara Ocidental',
  WS: 'Samoa',
  AS: 'Samoa Americana',
  PM: 'Saint Pierre e Miquelon',
  KN: 'São Cristóvão e Névis',
  SM: 'San Marino',
  SH: 'Santa Helena',
  LC: 'Santa Lúcia',
  BL: 'São Bartolomeu',
  MF: 'São Martinho (Parte Francesa)',
  SX: 'São Martinho (Parte Holandesa)',
  ST: 'São Tomé e Príncipe',
  VC: 'São Vicente e Granadinas',
  SN: 'Senegal',
  SL: 'Serra Leoa',
  RS: 'Sérvia',
  SC: 'Seychelles',
  SY: 'Síria',
  SO: 'Somália',
  LK: 'Sri Lanka',
  SZ: 'Suazilândia',
  SD: 'Sudão',
  SE: 'Suécia',
  CH: 'Suíça',
  SR: 'Suriname',
  SJ: 'Svalbard e Jan Mayen',
  TJ: 'Tajiquistão',
  TH: 'Tailândia',
  TW: 'Taiwan',
  TZ: 'Tanzânia',
  IO: 'Território Britânico do Oceano Índico',
  TF: 'Territórios Franceses do Sul',
  PS: 'Territórios Palestinos',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad e Tobago',
  TN: 'Tunísia',
  TM: 'Turcomenistão',
  TR: 'Turquia',
  TV: 'Tuvalu',
  UA: 'Ucrânia',
  UG: 'Uganda',
  UY: 'Uruguai',
  UZ: 'Uzbequistão',
  VU: 'Vanuatu',
  VA: 'Vaticano',
  VE: 'Venezuela',
  VN: 'Vietnã',
  WF: 'Wallis e Futuna',
  ZM: 'Zâmbia',
  ZW: 'Zimbábue',
};

export default (countryCode) => contryCodeToPortuguese[countryCode];
